### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135174"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    <span data-ttu-id="4ef23-101">Décrit un événement de Chaos est généré lorsqu’un événement inattendu se produit dans le moteur de Chaos.</span><span class="sxs-lookup"><span data-stu-id="4ef23-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>

    <span data-ttu-id="4ef23-102">Par exemple, en raison de l’instantané de cluster étant incohérent, lors de la défaillance d’une entité, le Chaos trouvé que l’entité a déjà généré une erreur--qui serait un événement inattendu.</span><span class="sxs-lookup"><span data-stu-id="4ef23-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: <span data-ttu-id="4ef23-103">Décrit pourquoi TestErrorChaosEvent a été généré.</span><span class="sxs-lookup"><span data-stu-id="4ef23-103">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="4ef23-104">Par exemple, le Chaos tente une partition de l’erreur mais détecte que la partition n’est plus une tolérance de panne, puis un TestErrorEvent est généré avec la raison indiquant que la partition n’est pas une tolérance de panne.</span><span class="sxs-lookup"><span data-stu-id="4ef23-104">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
